baseURL = 'https://straycircuits.com/'
languageCode = 'en-us'
title = 'Stray Circuits'
theme = 'relearn'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  disableLandingPageButton = true
  disableExplicitIndexURLs = true
  themeVariant = 'stray'

  [params.imageEffects]
    border = false
    dataurl = false
    inlinecontent = false
    lightbox = false
    shadow = false